version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    steps:
      - checkout
      - run:
          name: Check Working Directory
          command: echo $CIRCLE_WORKING_DIRECTORY

workflows:

  build_and_test:
    jobs:
      - build

